SET DEFINE OFF
SET SERVEROUTPUT ON

DECLARE
  PROCEDURE create_sequence_if_missing(p_name VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = UPPER(p_name);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE 'CREATE SEQUENCE ' || p_name || ' START WITH 1 NOCACHE';
      DBMS_OUTPUT.PUT_LINE('created sequence ' || p_name);
    ELSE
      DBMS_OUTPUT.PUT_LINE('sequence exists ' || p_name);
    END IF;
  END;

  PROCEDURE run_ddl_if_table_missing(p_table VARCHAR2, p_sql CLOB) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = UPPER(p_table);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE p_sql;
      DBMS_OUTPUT.PUT_LINE('created table ' || p_table);
    ELSE
      DBMS_OUTPUT.PUT_LINE('table exists ' || p_table);
    END IF;
  END;
BEGIN
  create_sequence_if_missing('SEQ_BL_PRODUCT_FAVORITES');
  create_sequence_if_missing('SEQ_BL_PRODUCT_RATINGS');
  create_sequence_if_missing('SEQ_BL_RECOMMENDATION_FEEDBACK');
  create_sequence_if_missing('SEQ_BL_USER_PRODUCT_EVENTS');

  run_ddl_if_table_missing('BL_PRODUCT_FAVORITES', q'[
    CREATE TABLE BL_PRODUCT_FAVORITES (
      FAVORITE_ID NUMBER PRIMARY KEY,
      MEMBER_ID   NUMBER NOT NULL,
      PRODUCT_ID  NUMBER NOT NULL,
      CREATED_AT  DATE DEFAULT SYSDATE,
      CONSTRAINT FK_PRODUCT_FAV_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES BL_MEMBERS(MEMBER_ID),
      CONSTRAINT FK_PRODUCT_FAV_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES BL_PRODUCTS(PRODUCT_ID),
      CONSTRAINT UQ_PRODUCT_FAV UNIQUE (MEMBER_ID, PRODUCT_ID)
    )
  ]');

  run_ddl_if_table_missing('BL_PRODUCT_RATINGS', q'[
    CREATE TABLE BL_PRODUCT_RATINGS (
      RATING_ID         NUMBER PRIMARY KEY,
      MEMBER_ID         NUMBER NOT NULL,
      PRODUCT_ID        NUMBER NOT NULL,
      RATING            NUMBER(2,1) NOT NULL,
      SKIN_TYPE_AT_TIME VARCHAR2(20),
      IRRITATION_YN     CHAR(1),
      REPURCHASE_YN     CHAR(1),
      REVIEW_TEXT       CLOB,
      CREATED_AT        DATE DEFAULT SYSDATE,
      UPDATED_AT        DATE,
      CONSTRAINT FK_PRODUCT_RATING_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES BL_MEMBERS(MEMBER_ID),
      CONSTRAINT FK_PRODUCT_RATING_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES BL_PRODUCTS(PRODUCT_ID),
      CONSTRAINT UQ_PRODUCT_RATING UNIQUE (MEMBER_ID, PRODUCT_ID),
      CONSTRAINT CK_PRODUCT_RATING_SCORE CHECK (RATING BETWEEN 1 AND 5),
      CONSTRAINT CK_PRODUCT_RATING_IRRITATION CHECK (IRRITATION_YN IS NULL OR IRRITATION_YN IN ('Y', 'N')),
      CONSTRAINT CK_PRODUCT_RATING_REPURCHASE CHECK (REPURCHASE_YN IS NULL OR REPURCHASE_YN IN ('Y', 'N'))
    )
  ]');

  run_ddl_if_table_missing('BL_RECOMMENDATION_FEEDBACK', q'[
    CREATE TABLE BL_RECOMMENDATION_FEEDBACK (
      FEEDBACK_ID       NUMBER PRIMARY KEY,
      MEMBER_ID         NUMBER NOT NULL,
      PRODUCT_ID        NUMBER NOT NULL,
      FEEDBACK_TYPE     VARCHAR2(30) NOT NULL,
      SKIN_TYPE_AT_TIME VARCHAR2(20),
      CREATED_AT        DATE DEFAULT SYSDATE,
      CONSTRAINT FK_REC_FB_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES BL_MEMBERS(MEMBER_ID),
      CONSTRAINT FK_REC_FB_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES BL_PRODUCTS(PRODUCT_ID),
      CONSTRAINT UQ_REC_FB_MEMBER_PRODUCT UNIQUE (MEMBER_ID, PRODUCT_ID),
      CONSTRAINT CK_REC_FB_TYPE CHECK (FEEDBACK_TYPE IN ('LIKE', 'DISLIKE', 'NOT_INTERESTED'))
    )
  ]');

  run_ddl_if_table_missing('BL_USER_PRODUCT_EVENTS', q'[
    CREATE TABLE BL_USER_PRODUCT_EVENTS (
      EVENT_ID          NUMBER PRIMARY KEY,
      MEMBER_ID         NUMBER NOT NULL,
      PRODUCT_ID        NUMBER NOT NULL,
      EVENT_TYPE        VARCHAR2(40) NOT NULL,
      EVENT_VALUE       VARCHAR2(200),
      SKIN_TYPE_AT_TIME VARCHAR2(20),
      CREATED_AT        DATE DEFAULT SYSDATE,
      CONSTRAINT FK_USER_EVENT_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES BL_MEMBERS(MEMBER_ID),
      CONSTRAINT FK_USER_EVENT_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES BL_PRODUCTS(PRODUCT_ID),
      CONSTRAINT CK_USER_EVENT_TYPE CHECK (EVENT_TYPE IN (
        'VIEW', 'DETAIL_VIEW', 'FAVORITE', 'UNFAVORITE', 'RATE', 'COMMENT',
        'RECOMMEND_LIKE', 'RECOMMEND_DISLIKE', 'NOT_INTERESTED', 'RECOMMEND_FEEDBACK'
      ))
    )
  ]');
END;
/

COMMIT;

SELECT table_name FROM user_tables WHERE table_name IN (
  'BL_PRODUCT_FAVORITES',
  'BL_PRODUCT_RATINGS',
  'BL_RECOMMENDATION_FEEDBACK',
  'BL_USER_PRODUCT_EVENTS'
) ORDER BY table_name;
